/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Second_trial;

/**
 *
 * @author hirwa
 */
public class NewJFrame extends javax.swing.JFrame {

    double  firstNumberIn; 
    double secondNumberIn;
    double resultOfOperation;
    String operationSign; 
    String theAnswer;
    String thequestion;
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        InputAndAnswerTextField = new javax.swing.JTextField();
        displayTextField = new javax.swing.JTextField();
        plusSignButton = new javax.swing.JButton();
        BackspaceButton = new javax.swing.JButton();
        subtractionSignButton = new javax.swing.JButton();
        multiplicationSignButton = new javax.swing.JButton();
        divisionSignButton = new javax.swing.JButton();
        equalSignButton = new javax.swing.JButton();
        nineButton = new javax.swing.JButton();
        sixButton = new javax.swing.JButton();
        threeButton = new javax.swing.JButton();
        dotSignButton = new javax.swing.JButton();
        eightButton = new javax.swing.JButton();
        sevenButton = new javax.swing.JButton();
        fourButton = new javax.swing.JButton();
        fiveButton = new javax.swing.JButton();
        twoButton = new javax.swing.JButton();
        oneButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hirwa's Calculator");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        InputAndAnswerTextField.setBackground(new java.awt.Color(153, 153, 153));
        InputAndAnswerTextField.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        InputAndAnswerTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        InputAndAnswerTextField.setBorder(null);

        displayTextField.setBackground(new java.awt.Color(153, 153, 153));
        displayTextField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        displayTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        displayTextField.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(InputAndAnswerTextField)
            .addComponent(displayTextField)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(displayTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InputAndAnswerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        plusSignButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        plusSignButton.setText("+");
        plusSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusSignButtonActionPerformed(evt);
            }
        });

        BackspaceButton.setText("Backspace");
        BackspaceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackspaceButtonActionPerformed(evt);
            }
        });

        subtractionSignButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        subtractionSignButton.setText("-");
        subtractionSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionSignButtonActionPerformed(evt);
            }
        });

        multiplicationSignButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        multiplicationSignButton.setText("x");
        multiplicationSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationSignButtonActionPerformed(evt);
            }
        });

        divisionSignButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        divisionSignButton.setText("/");
        divisionSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionSignButtonActionPerformed(evt);
            }
        });

        equalSignButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        equalSignButton.setText("=");
        equalSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalSignButtonActionPerformed(evt);
            }
        });

        nineButton.setBackground(new java.awt.Color(51, 51, 51));
        nineButton.setForeground(new java.awt.Color(255, 255, 255));
        nineButton.setMnemonic('9');
        nineButton.setText("9");
        nineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineButtonActionPerformed(evt);
            }
        });

        sixButton.setBackground(new java.awt.Color(51, 51, 51));
        sixButton.setForeground(new java.awt.Color(255, 255, 255));
        sixButton.setMnemonic('6');
        sixButton.setText("6");
        sixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixButtonActionPerformed(evt);
            }
        });

        threeButton.setBackground(new java.awt.Color(51, 51, 51));
        threeButton.setForeground(new java.awt.Color(255, 255, 255));
        threeButton.setMnemonic('3');
        threeButton.setText("3");
        threeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeButtonActionPerformed(evt);
            }
        });

        dotSignButton.setBackground(new java.awt.Color(51, 51, 51));
        dotSignButton.setForeground(new java.awt.Color(255, 255, 255));
        dotSignButton.setText(".");
        dotSignButton.setToolTipText("");
        dotSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotSignButtonActionPerformed(evt);
            }
        });

        eightButton.setBackground(new java.awt.Color(51, 51, 51));
        eightButton.setForeground(new java.awt.Color(255, 255, 255));
        eightButton.setMnemonic('8');
        eightButton.setText("8");
        eightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightButtonActionPerformed(evt);
            }
        });

        sevenButton.setBackground(new java.awt.Color(51, 51, 51));
        sevenButton.setForeground(new java.awt.Color(255, 255, 255));
        sevenButton.setMnemonic('7');
        sevenButton.setText("7");
        sevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenButtonActionPerformed(evt);
            }
        });

        fourButton.setBackground(new java.awt.Color(51, 51, 51));
        fourButton.setForeground(new java.awt.Color(255, 255, 255));
        fourButton.setMnemonic('4');
        fourButton.setText("4");
        fourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourButtonActionPerformed(evt);
            }
        });

        fiveButton.setBackground(new java.awt.Color(51, 51, 51));
        fiveButton.setForeground(new java.awt.Color(255, 255, 255));
        fiveButton.setMnemonic('5');
        fiveButton.setText("5");
        fiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveButtonActionPerformed(evt);
            }
        });

        twoButton.setBackground(new java.awt.Color(51, 51, 51));
        twoButton.setForeground(new java.awt.Color(255, 255, 255));
        twoButton.setMnemonic('2');
        twoButton.setText("2");
        twoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoButtonActionPerformed(evt);
            }
        });

        oneButton.setBackground(new java.awt.Color(51, 51, 51));
        oneButton.setForeground(new java.awt.Color(255, 255, 255));
        oneButton.setMnemonic('1');
        oneButton.setText("1");
        oneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneButtonActionPerformed(evt);
            }
        });

        zeroButton.setBackground(new java.awt.Color(51, 51, 51));
        zeroButton.setForeground(new java.awt.Color(255, 255, 255));
        zeroButton.setMnemonic('0');
        zeroButton.setText("0");
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });

        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("CALCULATOR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel1)
                                .addGap(0, 94, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fourButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sevenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dotSignButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(zeroButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(twoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fiveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(eightButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sixButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nineButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(multiplicationSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subtractionSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(divisionSignButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(equalSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(plusSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(BackspaceButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackspaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(divisionSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(multiplicationSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtractionSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dotSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(equalSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plusSignButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        InputAndAnswerTextField.setText("");
        displayTextField.setText("");
        firstNumberIn = 0;
        secondNumberIn = 0;
        operationSign = "";
        theAnswer = "";
        thequestion = "";
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        String zero = zeroButton.getText();
        InputAndAnswerTextField.setText(InputAndAnswerTextField.getText()+""+zero);
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void oneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneButtonActionPerformed
        String one = oneButton.getText();
        InputAndAnswerTextField.setText(InputAndAnswerTextField.getText()+""+one);
    }//GEN-LAST:event_oneButtonActionPerformed

    private void twoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoButtonActionPerformed
        String two = twoButton.getText();
        InputAndAnswerTextField.setText(InputAndAnswerTextField.getText()+""+two);
    }//GEN-LAST:event_twoButtonActionPerformed

    private void fiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveButtonActionPerformed
        String five = fiveButton.getText();
        InputAndAnswerTextField.setText(InputAndAnswerTextField.getText()+""+five);
    }//GEN-LAST:event_fiveButtonActionPerformed

    private void fourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourButtonActionPerformed
        String four = fourButton.getText();
        InputAndAnswerTextField.setText(InputAndAnswerTextField.getText()+""+four);
    }//GEN-LAST:event_fourButtonActionPerformed

    private void sevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenButtonActionPerformed
        String seven = sevenButton.getText();
        InputAndAnswerTextField.setText(InputAndAnswerTextField.getText()+""+seven);
    }//GEN-LAST:event_sevenButtonActionPerformed

    private void eightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightButtonActionPerformed
        String eight = eightButton.getText();
        InputAndAnswerTextField.setText(InputAndAnswerTextField.getText()+""+eight);
    }//GEN-LAST:event_eightButtonActionPerformed

    private void dotSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotSignButtonActionPerformed
        String thedot = dotSignButton.getText();
        InputAndAnswerTextField.setText(InputAndAnswerTextField.getText()+""+thedot);
    }//GEN-LAST:event_dotSignButtonActionPerformed

    private void threeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeButtonActionPerformed
        String three = threeButton.getText();
        InputAndAnswerTextField.setText(InputAndAnswerTextField.getText()+""+three);
    }//GEN-LAST:event_threeButtonActionPerformed

    private void sixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixButtonActionPerformed
        String six = sixButton.getText();
        InputAndAnswerTextField.setText(InputAndAnswerTextField.getText()+""+six);
    }//GEN-LAST:event_sixButtonActionPerformed

    private void nineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineButtonActionPerformed
        String nine = nineButton.getText();
        InputAndAnswerTextField.setText(InputAndAnswerTextField.getText()+""+nine);
    }//GEN-LAST:event_nineButtonActionPerformed

    private void equalSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalSignButtonActionPerformed
        String equalSign = "=";
        thequestion = displayTextField.getText()+""+InputAndAnswerTextField.getText()+""+equalSign;
        displayTextField.setText(thequestion);
        secondNumberIn = Double.parseDouble(InputAndAnswerTextField.getText());
        InputAndAnswerTextField.setText("");
        creatingResults(operationSign);
        InputAndAnswerTextField.setText(theAnswer);
    }//GEN-LAST:event_equalSignButtonActionPerformed

    private void divisionSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionSignButtonActionPerformed
        displayTextField.setText("");
        operationSign = "/";
        thequestion = displayTextField.getText()+""+InputAndAnswerTextField.getText()+""+operationSign;
        displayTextField.setText(thequestion);
        firstNumberIn = Double.parseDouble(InputAndAnswerTextField.getText());
        InputAndAnswerTextField.setText("");
    }//GEN-LAST:event_divisionSignButtonActionPerformed

    private void multiplicationSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationSignButtonActionPerformed
        displayTextField.setText("");
        operationSign = "x";
        thequestion = displayTextField.getText()+""+InputAndAnswerTextField.getText()+""+operationSign;
        displayTextField.setText(thequestion);
        firstNumberIn = Double.parseDouble(InputAndAnswerTextField.getText());
        InputAndAnswerTextField.setText("");
    }//GEN-LAST:event_multiplicationSignButtonActionPerformed

    private void subtractionSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionSignButtonActionPerformed
        displayTextField.setText("");
        operationSign = "-";
        thequestion = displayTextField.getText()+""+InputAndAnswerTextField.getText()+""+operationSign;
        displayTextField.setText(thequestion);
        firstNumberIn = Double.parseDouble(InputAndAnswerTextField.getText());
        InputAndAnswerTextField.setText("");
    }//GEN-LAST:event_subtractionSignButtonActionPerformed

    private void BackspaceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackspaceButtonActionPerformed
        String newbackspacevalue = null;
        if (InputAndAnswerTextField.getText().length()>0) {
            StringBuilder strb = new StringBuilder(InputAndAnswerTextField.getText());
            strb.deleteCharAt(InputAndAnswerTextField.getText().length()-1);
            newbackspacevalue = strb.toString();
            InputAndAnswerTextField.setText(newbackspacevalue);
        }
    }//GEN-LAST:event_BackspaceButtonActionPerformed

    //OPERATION SIGNS
    
    private void plusSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusSignButtonActionPerformed
        //When you click on an arithmetic sign, the text text with was in the displaytextfield
        //and that which was in the inputandanswertextfield are all put in the displaytextfield and the inputandanswerfield is left empty to leave room for other data to be added.
        //StringBuilder strblr = new StringBuilder(displayTextField.getText() );
        //strblr.charAt(displayTextField.getText().length()-1);
        //String theSign = strblr.toString();
        //if(theSign == "="){

            displayTextField.setText("");
            operationSign = "+";
            thequestion = displayTextField.getText()+""+InputAndAnswerTextField.getText()+""+operationSign;
            displayTextField.setText(thequestion);
            firstNumberIn = Double.parseDouble(InputAndAnswerTextField.getText());
            InputAndAnswerTextField.setText("");

    }//GEN-LAST:event_plusSignButtonActionPerformed
   
    public String creatingResults(String sign){
        
        switch (sign) {
            case "+":
                resultOfOperation = firstNumberIn+secondNumberIn;
                theAnswer = String.format("%.2f", resultOfOperation);
                return theAnswer;
            case "-":
                resultOfOperation = firstNumberIn-secondNumberIn;
                theAnswer = String.format("%.2f", resultOfOperation);
                return theAnswer;
            case "x":
                resultOfOperation = firstNumberIn*secondNumberIn;
                theAnswer = String.format("%.2f", resultOfOperation);
                return theAnswer;
            case "/":
                resultOfOperation = firstNumberIn/secondNumberIn;
                theAnswer = String.format("%.2f", resultOfOperation);
                return theAnswer;
             default:
                 theAnswer = String.format("%.2f", firstNumberIn);
                 return theAnswer;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackspaceButton;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField InputAndAnswerTextField;
    private javax.swing.JTextField displayTextField;
    private javax.swing.JButton divisionSignButton;
    private javax.swing.JButton dotSignButton;
    private javax.swing.JButton eightButton;
    private javax.swing.JButton equalSignButton;
    private javax.swing.JButton fiveButton;
    private javax.swing.JButton fourButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton multiplicationSignButton;
    private javax.swing.JButton nineButton;
    private javax.swing.JButton oneButton;
    private javax.swing.JButton plusSignButton;
    private javax.swing.JButton sevenButton;
    private javax.swing.JButton sixButton;
    private javax.swing.JButton subtractionSignButton;
    private javax.swing.JButton threeButton;
    private javax.swing.JButton twoButton;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
