/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author hirwa
 */
public class MouseEvent extends javax.swing.JFrame {

    /**
     * Creates new form MouseEvent
     */
    public MouseEvent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        touchPanel = new javax.swing.JPanel();
        displayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        touchPanel.setBackground(new java.awt.Color(204, 204, 255));
        touchPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                touchPanelMouseMoved(evt);
            }
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                touchPanelMouseDragged(evt);
            }
        });
        touchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                touchPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                touchPanelMouseReleased(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                touchPanelMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                touchPanelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                touchPanelMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout touchPanelLayout = new javax.swing.GroupLayout(touchPanel);
        touchPanel.setLayout(touchPanelLayout);
        touchPanelLayout.setHorizontalGroup(
            touchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        touchPanelLayout.setVerticalGroup(
            touchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(touchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(displayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(touchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(displayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void touchPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_touchPanelMouseClicked
        // TODO add your handling code here:
        displayLabel.setText(String.format("Mouse clicked at %d, %d", evt.getX(),evt.getY()));
    }//GEN-LAST:event_touchPanelMouseClicked

    private void touchPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_touchPanelMouseEntered
        // TODO add your handling code here:
        displayLabel.setText(String.format("Mouse entered panel at %d, %d", evt.getX(),evt.getY()));
    }//GEN-LAST:event_touchPanelMouseEntered

    private void touchPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_touchPanelMouseExited
        // TODO add your handling code here:
        displayLabel.setText("Mouse exited the panel");
    }//GEN-LAST:event_touchPanelMouseExited

    private void touchPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_touchPanelMousePressed
        // TODO add your handling code here:
        displayLabel.setText(String.format("Mouse  pressed at %d, %d", evt.getX(),evt.getY()));
    }//GEN-LAST:event_touchPanelMousePressed

    private void touchPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_touchPanelMouseReleased
        // TODO add your handling code here:
        displayLabel.setText("Mouse released");
    }//GEN-LAST:event_touchPanelMouseReleased

    private void touchPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_touchPanelMouseDragged
        // TODO add your handling code here:
        displayLabel.setText(String.format("Mouse dragging at %d, %d", evt.getX(),evt.getY()));
    }//GEN-LAST:event_touchPanelMouseDragged

    private void touchPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_touchPanelMouseMoved
        // TODO add your handling code here:
        displayLabel.setText(String.format("Mouse moving at %d, %d", evt.getX(),evt.getY()));
    }//GEN-LAST:event_touchPanelMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MouseEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MouseEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MouseEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MouseEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MouseEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel displayLabel;
    private javax.swing.JPanel touchPanel;
    // End of variables declaration//GEN-END:variables
}
