/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Work;

/**
 *
 * @author hirwa
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProjectToolBar = new javax.swing.JToolBar();
        ReportTool = new javax.swing.JButton();
        ChartTool = new javax.swing.JButton();
        ClearTool = new javax.swing.JButton();
        DataTool = new javax.swing.JButton();
        OkTool = new javax.swing.JButton();
        PrintTool = new javax.swing.JButton();
        SignOutTool = new javax.swing.JButton();
        CalendarIcon = new javax.swing.JLabel();
        TodayDate = new javax.swing.JLabel();
        tableScrollPanel = new javax.swing.JScrollPane();
        MyTable = new javax.swing.JTable();
        PumpDataPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PumpIdTextField = new javax.swing.JTextField();
        DeleteButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        DateTextField = new javax.swing.JTextField();
        Pressure1TextField = new javax.swing.JTextField();
        Pressure2TextField = new javax.swing.JTextField();
        Pressure3TextField = new javax.swing.JTextField();
        VolumeFlowTextField = new javax.swing.JTextField();
        TemperatureTextField = new javax.swing.JTextField();
        RotationalSpeedTextField = new javax.swing.JTextField();
        TorqueTextField = new javax.swing.JTextField();
        MiddlePanel = new javax.swing.JPanel();
        TabbedPanes = new javax.swing.JTabbedPane();
        RemarkPanelTab = new javax.swing.JPanel();
        DecisionPanelTab = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        UserInputPanelTab = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ParameterComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TotalAvailabilityPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PercentageTextField = new javax.swing.JTextField();
        PercentageProgressBar = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        SearchPanel = new javax.swing.JPanel();
        SearchTextField = new javax.swing.JTextField();
        SearchIcon = new javax.swing.JButton();
        Range1TextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Range2TextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        UserInputDateRange1 = new com.toedter.calendar.JDateChooser();
        UserInputDateRange2 = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        ButtonsPanel = new javax.swing.JPanel();
        ReportButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        ChartButton = new javax.swing.JButton();
        DataButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        OkButton = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        TrafficLigthLabel = new javax.swing.JLabel();
        OverAllLight1TextField = new javax.swing.JTextField();
        OverAllLight2TextField = new javax.swing.JTextField();
        OverAllLight3TextField = new javax.swing.JTextField();
        IndicatorPanel = new javax.swing.JPanel();
        Pressure1Slider = new javax.swing.JSlider();
        Pressure1Panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Pressure2Slider = new javax.swing.JSlider();
        Pressure3Slider = new javax.swing.JSlider();
        VolumeFlowSlider = new javax.swing.JSlider();
        TemperatureSlider = new javax.swing.JSlider();
        RotationalSpeedSlider = new javax.swing.JSlider();
        TorqueSlider = new javax.swing.JSlider();
        Pressure2Panel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        Pressure3Panel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        VolumeFlowPanel = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        TemperaturePanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        RotationalSpeedPanel = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        TorquePanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        ProjectMenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        HelpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hirwa");

        ProjectToolBar.setRollover(true);

        ReportTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-1.png"))); // NOI18N
        ReportTool.setText("Report");
        ReportTool.setFocusable(false);
        ReportTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ReportTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ReportTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportToolActionPerformed(evt);
            }
        });
        ProjectToolBar.add(ReportTool);

        ChartTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/chart-2.png"))); // NOI18N
        ChartTool.setText("Chart");
        ChartTool.setFocusable(false);
        ChartTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ChartTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ProjectToolBar.add(ChartTool);

        ClearTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/clean-1.jpg"))); // NOI18N
        ClearTool.setText("Clear");
        ClearTool.setFocusable(false);
        ClearTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ClearTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ProjectToolBar.add(ClearTool);

        DataTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/data-2.jpg"))); // NOI18N
        DataTool.setText("Data");
        DataTool.setFocusable(false);
        DataTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DataTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ProjectToolBar.add(DataTool);

        OkTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ok-1.jpg"))); // NOI18N
        OkTool.setText("Ok");
        OkTool.setFocusable(false);
        OkTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        OkTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ProjectToolBar.add(OkTool);

        PrintTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/print-1.jpg"))); // NOI18N
        PrintTool.setText("Print");
        PrintTool.setFocusable(false);
        PrintTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PrintTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ProjectToolBar.add(PrintTool);

        SignOutTool.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/signout-1.jpg"))); // NOI18N
        SignOutTool.setText("Sign Out");
        SignOutTool.setFocusable(false);
        SignOutTool.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignOutTool.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ProjectToolBar.add(SignOutTool);

        CalendarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/calendar-2.jpg"))); // NOI18N
        ProjectToolBar.add(CalendarIcon);

        TodayDate.setFont(new java.awt.Font("URW Chancery L", 1, 24)); // NOI18N
        TodayDate.setForeground(new java.awt.Color(0, 153, 0));
        TodayDate.setText("                                                      Date: 29/2/2012");
        ProjectToolBar.add(TodayDate);

        MyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2010-01-01", "4", "9 ", "134", "36", "38", "5522", "16"},
                {"2", "2010-01-02", " 7", "4", "254", "306", "34", "5933", "69"},
                {"3", "2010-01-03", " 13", "4", "255", "101", "48", "2646", "20"},
                {"4", "2010-01-04", " 4", "11", "21", "380", "58", "5841", "7"},
                {"5", "2010-01-05", " 10", "4", "294", "99", "8", "2024", "85"},
                {"6", "2010-01-06", " 6", "8", "349", "354", "35", "3856", "123"},
                {"7", "2010-01-07", " 5", "7", "106", "354", "42", "4561", "27"},
                {"8", "2010-01-08", " 3", "9", "185", "600", "16", "1670", "21"},
                {"9", "2010-01-09", " 7", "3", "361", "253", "50", "2972", "90"},
                {"10", "2010-01-10", " 0", "8", "328", "14", "35", "42", "145"},
                {null, null, null, "", null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "idpump", "Date", "Pressure1", "Pressure2", "Pressure 3", "VolumeFlow", "Temperature", "RotationalSpeed", "Torque"
            }
        ));
        tableScrollPanel.setViewportView(MyTable);

        PumpDataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pump Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(51, 102, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Pump Id");

        PumpIdTextField.setText("1");

        DeleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Fifth icon.png"))); // NOI18N
        DeleteButton.setText("Delete Data");

        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save-1.jpg"))); // NOI18N
        SaveButton.setText("Save New Data");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setText("Date");

        jLabel11.setFont(new java.awt.Font("DejaVu Sans", 0, 12)); // NOI18N
        jLabel11.setText("Pressure1");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setText("Pressure2");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setText("Pressure 3");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel14.setText("VolumeFlow");

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setText("Temperature (C)");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel16.setText("RotationalSpeed");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel17.setText("Torque (Nm)");

        DateTextField.setText("2010-10-10");

        Pressure1TextField.setText("4");

        Pressure2TextField.setText("9");
        Pressure2TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pressure2TextFieldActionPerformed(evt);
            }
        });

        Pressure3TextField.setText("134");

        VolumeFlowTextField.setText("36");
        VolumeFlowTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeFlowTextFieldActionPerformed(evt);
            }
        });

        TemperatureTextField.setText("34");

        RotationalSpeedTextField.setText("5522");

        TorqueTextField.setText("16");

        javax.swing.GroupLayout PumpDataPanelLayout = new javax.swing.GroupLayout(PumpDataPanel);
        PumpDataPanel.setLayout(PumpDataPanelLayout);
        PumpDataPanelLayout.setHorizontalGroup(
            PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PumpDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PumpDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TorqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PumpDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RotationalSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PumpDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TemperatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PumpDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VolumeFlowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PumpDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pressure3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PumpDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pressure2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PumpDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pressure1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PumpDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PumpDataPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PumpIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
            .addGroup(PumpDataPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PumpDataPanelLayout.createSequentialGroup()
                        .addComponent(DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(SaveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PumpDataPanelLayout.setVerticalGroup(
            PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PumpDataPanelLayout.createSequentialGroup()
                .addGroup(PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PumpDataPanelLayout.createSequentialGroup()
                        .addGroup(PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PumpDataPanelLayout.createSequentialGroup()
                                .addGroup(PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PumpDataPanelLayout.createSequentialGroup()
                                        .addGroup(PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel1)
                                            .addComponent(PumpIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel10)
                                            .addComponent(DateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11))
                                    .addComponent(Pressure1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12))
                            .addComponent(Pressure2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PumpDataPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13))
                            .addGroup(PumpDataPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Pressure3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(VolumeFlowTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(TemperatureTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addComponent(RotationalSpeedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PumpDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TorqueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SaveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DeleteButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        MiddlePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TabbedPanes.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout RemarkPanelTabLayout = new javax.swing.GroupLayout(RemarkPanelTab);
        RemarkPanelTab.setLayout(RemarkPanelTabLayout);
        RemarkPanelTabLayout.setHorizontalGroup(
            RemarkPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        RemarkPanelTabLayout.setVerticalGroup(
            RemarkPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        TabbedPanes.addTab("Remarks", RemarkPanelTab);

        javax.swing.GroupLayout DecisionPanelTabLayout = new javax.swing.GroupLayout(DecisionPanelTab);
        DecisionPanelTab.setLayout(DecisionPanelTabLayout);
        DecisionPanelTabLayout.setHorizontalGroup(
            DecisionPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        DecisionPanelTabLayout.setVerticalGroup(
            DecisionPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        TabbedPanes.addTab("Decision Making", DecisionPanelTab);

        UserInputPanelTab.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Input", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Enter Parameter");

        ParameterComboBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ParameterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "None ", "Everything" }));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Date Range From");

        TotalAvailabilityPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Total Availability", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("%");

        PercentageTextField.setText("99.5");

        PercentageProgressBar.setForeground(new java.awt.Color(255, 153, 0));
        PercentageProgressBar.setValue(99);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Avatar Icon.png"))); // NOI18N

        javax.swing.GroupLayout TotalAvailabilityPanelLayout = new javax.swing.GroupLayout(TotalAvailabilityPanel);
        TotalAvailabilityPanel.setLayout(TotalAvailabilityPanelLayout);
        TotalAvailabilityPanelLayout.setHorizontalGroup(
            TotalAvailabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalAvailabilityPanelLayout.createSequentialGroup()
                .addGroup(TotalAvailabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PercentageProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TotalAvailabilityPanelLayout.createSequentialGroup()
                        .addComponent(PercentageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TotalAvailabilityPanelLayout.setVerticalGroup(
            TotalAvailabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalAvailabilityPanelLayout.createSequentialGroup()
                .addGroup(TotalAvailabilityPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PercentageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(PercentageProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalAvailabilityPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        SearchPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans Condensed", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        SearchIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search-1.jpg"))); // NOI18N

        javax.swing.GroupLayout SearchPanelLayout = new javax.swing.GroupLayout(SearchPanel);
        SearchPanel.setLayout(SearchPanelLayout);
        SearchPanelLayout.setHorizontalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SearchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        SearchPanelLayout.setVerticalGroup(
            SearchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SearchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(SearchIcon)
        );

        jLabel18.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel18.setText("Enter Range");

        jLabel19.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel19.setText("to");

        jLabel20.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel20.setText("to");

        javax.swing.GroupLayout UserInputPanelTabLayout = new javax.swing.GroupLayout(UserInputPanelTab);
        UserInputPanelTab.setLayout(UserInputPanelTabLayout);
        UserInputPanelTabLayout.setHorizontalGroup(
            UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInputPanelTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UserInputPanelTabLayout.createSequentialGroup()
                        .addGroup(UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel18))
                        .addGap(25, 25, 25)
                        .addGroup(UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(UserInputPanelTabLayout.createSequentialGroup()
                                .addComponent(Range1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(Range2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ParameterComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(UserInputPanelTabLayout.createSequentialGroup()
                        .addGroup(UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UserInputDateRange1, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(UserInputDateRange2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(UserInputPanelTabLayout.createSequentialGroup()
                .addGroup(UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TotalAvailabilityPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SearchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        UserInputPanelTabLayout.setVerticalGroup(
            UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInputPanelTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ParameterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Range1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(Range2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(UserInputDateRange1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserInputPanelTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20)
                    .addComponent(UserInputDateRange2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalAvailabilityPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserInputPanelTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserInputPanelTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TabbedPanes.addTab("User Input", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        TabbedPanes.addTab("Parameter MIN MAX Values", jPanel6);

        javax.swing.GroupLayout MiddlePanelLayout = new javax.swing.GroupLayout(MiddlePanel);
        MiddlePanel.setLayout(MiddlePanelLayout);
        MiddlePanelLayout.setHorizontalGroup(
            MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPanes))
        );
        MiddlePanelLayout.setVerticalGroup(
            MiddlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiddlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPanes))
        );

        ButtonsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        ReportButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ReportButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/report-1.png"))); // NOI18N
        ReportButton.setText("Report");

        CloseButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        CloseButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close-1.jpg"))); // NOI18N
        CloseButton.setText("Close");

        ChartButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ChartButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/chart-2.png"))); // NOI18N
        ChartButton.setText("Chart");

        DataButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        DataButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/data-2.jpg"))); // NOI18N
        DataButton.setText("Data");

        ClearButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/clean-1.jpg"))); // NOI18N
        ClearButton.setText("Clear");

        OkButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        OkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ok-1.jpg"))); // NOI18N
        OkButton.setText("Ok");

        javax.swing.GroupLayout ButtonsPanelLayout = new javax.swing.GroupLayout(ButtonsPanel);
        ButtonsPanel.setLayout(ButtonsPanelLayout);
        ButtonsPanelLayout.setHorizontalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(CloseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ChartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ButtonsPanelLayout.setVerticalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReportButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ChartButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DataButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClearButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OkButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Overall Lights", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 51, 255))); // NOI18N

        TrafficLigthLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Traffic-1.jpg"))); // NOI18N

        OverAllLight1TextField.setText("0");

        OverAllLight2TextField.setText("0");

        OverAllLight3TextField.setBackground(new java.awt.Color(0, 255, 51));
        OverAllLight3TextField.setText("7");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TrafficLigthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OverAllLight1TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OverAllLight2TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OverAllLight3TextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(OverAllLight1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OverAllLight2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OverAllLight3TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TrafficLigthLabel))
                .addGap(12, 12, 12))
        );

        IndicatorPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indicator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 102, 255))); // NOI18N

        Pressure1Slider.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Pressure1Slider.setMajorTickSpacing(5);
        Pressure1Slider.setMaximum(20);
        Pressure1Slider.setMinorTickSpacing(1);
        Pressure1Slider.setPaintLabels(true);
        Pressure1Slider.setPaintTicks(true);
        Pressure1Slider.setValue(4);

        Pressure1Panel.setBackground(new java.awt.Color(0, 255, 0));
        Pressure1Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pressure 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel7.setText("4 Bar");

        javax.swing.GroupLayout Pressure1PanelLayout = new javax.swing.GroupLayout(Pressure1Panel);
        Pressure1Panel.setLayout(Pressure1PanelLayout);
        Pressure1PanelLayout.setHorizontalGroup(
            Pressure1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pressure1PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pressure1PanelLayout.setVerticalGroup(
            Pressure1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7)
        );

        Pressure2Slider.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Pressure2Slider.setMajorTickSpacing(5);
        Pressure2Slider.setMaximum(15);
        Pressure2Slider.setMinorTickSpacing(1);
        Pressure2Slider.setPaintLabels(true);
        Pressure2Slider.setPaintTicks(true);
        Pressure2Slider.setValue(9);

        Pressure3Slider.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Pressure3Slider.setMajorTickSpacing(250);
        Pressure3Slider.setMaximum(500);
        Pressure3Slider.setMinorTickSpacing(100);
        Pressure3Slider.setPaintLabels(true);
        Pressure3Slider.setPaintTicks(true);
        Pressure3Slider.setValue(130);

        VolumeFlowSlider.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        VolumeFlowSlider.setMajorTickSpacing(200);
        VolumeFlowSlider.setMaximum(600);
        VolumeFlowSlider.setMinorTickSpacing(100);
        VolumeFlowSlider.setPaintLabels(true);
        VolumeFlowSlider.setPaintTicks(true);
        VolumeFlowSlider.setValue(40);

        TemperatureSlider.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TemperatureSlider.setMajorTickSpacing(20);
        TemperatureSlider.setMaximum(60);
        TemperatureSlider.setMinorTickSpacing(10);
        TemperatureSlider.setPaintLabels(true);
        TemperatureSlider.setPaintTicks(true);
        TemperatureSlider.setValue(39);

        RotationalSpeedSlider.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        RotationalSpeedSlider.setMajorTickSpacing(2000);
        RotationalSpeedSlider.setMaximum(7000);
        RotationalSpeedSlider.setMinorTickSpacing(1000);
        RotationalSpeedSlider.setPaintLabels(true);
        RotationalSpeedSlider.setPaintTicks(true);
        RotationalSpeedSlider.setValue(5500);

        TorqueSlider.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        TorqueSlider.setMajorTickSpacing(100);
        TorqueSlider.setMaximum(250);
        TorqueSlider.setMinorTickSpacing(50);
        TorqueSlider.setPaintLabels(true);
        TorqueSlider.setPaintTicks(true);
        TorqueSlider.setValue(20);

        Pressure2Panel.setBackground(new java.awt.Color(0, 255, 0));
        Pressure2Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pressure2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel21.setText("9 Bar");

        javax.swing.GroupLayout Pressure2PanelLayout = new javax.swing.GroupLayout(Pressure2Panel);
        Pressure2Panel.setLayout(Pressure2PanelLayout);
        Pressure2PanelLayout.setHorizontalGroup(
            Pressure2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pressure2PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pressure2PanelLayout.setVerticalGroup(
            Pressure2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pressure2PanelLayout.createSequentialGroup()
                .addComponent(jLabel21)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        Pressure3Panel.setBackground(new java.awt.Color(0, 255, 0));
        Pressure3Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pressure3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel22.setText("134 Bar");

        javax.swing.GroupLayout Pressure3PanelLayout = new javax.swing.GroupLayout(Pressure3Panel);
        Pressure3Panel.setLayout(Pressure3PanelLayout);
        Pressure3PanelLayout.setHorizontalGroup(
            Pressure3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pressure3PanelLayout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Pressure3PanelLayout.setVerticalGroup(
            Pressure3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pressure3PanelLayout.createSequentialGroup()
                .addComponent(jLabel22)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        VolumeFlowPanel.setBackground(new java.awt.Color(0, 255, 0));
        VolumeFlowPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vol.Flow", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N

        jLabel23.setText("36 m/h");

        javax.swing.GroupLayout VolumeFlowPanelLayout = new javax.swing.GroupLayout(VolumeFlowPanel);
        VolumeFlowPanel.setLayout(VolumeFlowPanelLayout);
        VolumeFlowPanelLayout.setHorizontalGroup(
            VolumeFlowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolumeFlowPanelLayout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        VolumeFlowPanelLayout.setVerticalGroup(
            VolumeFlowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VolumeFlowPanelLayout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        TemperaturePanel.setBackground(new java.awt.Color(0, 255, 0));
        TemperaturePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Temperature", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel24.setText("38oC");

        javax.swing.GroupLayout TemperaturePanelLayout = new javax.swing.GroupLayout(TemperaturePanel);
        TemperaturePanel.setLayout(TemperaturePanelLayout);
        TemperaturePanelLayout.setHorizontalGroup(
            TemperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TemperaturePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TemperaturePanelLayout.setVerticalGroup(
            TemperaturePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TemperaturePanelLayout.createSequentialGroup()
                .addComponent(jLabel24)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        RotationalSpeedPanel.setBackground(new java.awt.Color(0, 255, 0));
        RotationalSpeedPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rot.Speed", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel25.setText("5522 rpm");

        javax.swing.GroupLayout RotationalSpeedPanelLayout = new javax.swing.GroupLayout(RotationalSpeedPanel);
        RotationalSpeedPanel.setLayout(RotationalSpeedPanelLayout);
        RotationalSpeedPanelLayout.setHorizontalGroup(
            RotationalSpeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RotationalSpeedPanelLayout.createSequentialGroup()
                .addComponent(jLabel25)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        RotationalSpeedPanelLayout.setVerticalGroup(
            RotationalSpeedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RotationalSpeedPanelLayout.createSequentialGroup()
                .addComponent(jLabel25)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        TorquePanel.setBackground(new java.awt.Color(0, 255, 0));
        TorquePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Torque", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel26.setText("16 Nm");

        javax.swing.GroupLayout TorquePanelLayout = new javax.swing.GroupLayout(TorquePanel);
        TorquePanel.setLayout(TorquePanelLayout);
        TorquePanelLayout.setHorizontalGroup(
            TorquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TorquePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TorquePanelLayout.setVerticalGroup(
            TorquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TorquePanelLayout.createSequentialGroup()
                .addComponent(jLabel26)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout IndicatorPanelLayout = new javax.swing.GroupLayout(IndicatorPanel);
        IndicatorPanel.setLayout(IndicatorPanelLayout);
        IndicatorPanelLayout.setHorizontalGroup(
            IndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndicatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TorqueSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(RotationalSpeedSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(TemperatureSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(VolumeFlowSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Pressure3Slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Pressure2Slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Pressure1Slider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(IndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VolumeFlowPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pressure1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pressure2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pressure3Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TemperaturePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RotationalSpeedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TorquePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        IndicatorPanelLayout.setVerticalGroup(
            IndicatorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndicatorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pressure1Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pressure2Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pressure3Slider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(VolumeFlowSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(TemperatureSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(RotationalSpeedSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(TorqueSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(IndicatorPanelLayout.createSequentialGroup()
                .addComponent(Pressure1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pressure2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pressure3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VolumeFlowPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TemperaturePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RotationalSpeedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TorquePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        FileMenu.setText("File");
        ProjectMenuBar.add(FileMenu);

        EditMenu.setText("Edit");
        ProjectMenuBar.add(EditMenu);

        HelpMenu.setText("Help");
        ProjectMenuBar.add(HelpMenu);

        setJMenuBar(ProjectMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ProjectToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 1077, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PumpDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(MiddlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(6, 6, 6)
                .addComponent(IndicatorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ProjectToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tableScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PumpDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MiddlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(IndicatorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReportToolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportToolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReportToolActionPerformed

    private void Pressure2TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pressure2TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pressure2TextFieldActionPerformed

    private void VolumeFlowTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeFlowTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolumeFlowTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JLabel CalendarIcon;
    private javax.swing.JButton ChartButton;
    private javax.swing.JButton ChartTool;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton ClearTool;
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton DataButton;
    private javax.swing.JButton DataTool;
    private javax.swing.JTextField DateTextField;
    private javax.swing.JPanel DecisionPanelTab;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JPanel IndicatorPanel;
    private javax.swing.JPanel MiddlePanel;
    private javax.swing.JTable MyTable;
    private javax.swing.JButton OkButton;
    private javax.swing.JButton OkTool;
    private javax.swing.JTextField OverAllLight1TextField;
    private javax.swing.JTextField OverAllLight2TextField;
    private javax.swing.JTextField OverAllLight3TextField;
    private javax.swing.JComboBox<String> ParameterComboBox;
    private javax.swing.JProgressBar PercentageProgressBar;
    private javax.swing.JTextField PercentageTextField;
    private javax.swing.JPanel Pressure1Panel;
    private javax.swing.JSlider Pressure1Slider;
    private javax.swing.JTextField Pressure1TextField;
    private javax.swing.JPanel Pressure2Panel;
    private javax.swing.JSlider Pressure2Slider;
    private javax.swing.JTextField Pressure2TextField;
    private javax.swing.JPanel Pressure3Panel;
    private javax.swing.JSlider Pressure3Slider;
    private javax.swing.JTextField Pressure3TextField;
    private javax.swing.JButton PrintTool;
    private javax.swing.JMenuBar ProjectMenuBar;
    private javax.swing.JToolBar ProjectToolBar;
    private javax.swing.JPanel PumpDataPanel;
    private javax.swing.JTextField PumpIdTextField;
    private javax.swing.JTextField Range1TextField;
    private javax.swing.JTextField Range2TextField;
    private javax.swing.JPanel RemarkPanelTab;
    private javax.swing.JButton ReportButton;
    private javax.swing.JButton ReportTool;
    private javax.swing.JPanel RotationalSpeedPanel;
    private javax.swing.JSlider RotationalSpeedSlider;
    private javax.swing.JTextField RotationalSpeedTextField;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton SearchIcon;
    private javax.swing.JPanel SearchPanel;
    private javax.swing.JTextField SearchTextField;
    private javax.swing.JButton SignOutTool;
    private javax.swing.JTabbedPane TabbedPanes;
    private javax.swing.JPanel TemperaturePanel;
    private javax.swing.JSlider TemperatureSlider;
    private javax.swing.JTextField TemperatureTextField;
    private javax.swing.JLabel TodayDate;
    private javax.swing.JPanel TorquePanel;
    private javax.swing.JSlider TorqueSlider;
    private javax.swing.JTextField TorqueTextField;
    private javax.swing.JPanel TotalAvailabilityPanel;
    private javax.swing.JLabel TrafficLigthLabel;
    private com.toedter.calendar.JDateChooser UserInputDateRange1;
    private com.toedter.calendar.JDateChooser UserInputDateRange2;
    private javax.swing.JPanel UserInputPanelTab;
    private javax.swing.JPanel VolumeFlowPanel;
    private javax.swing.JSlider VolumeFlowSlider;
    private javax.swing.JTextField VolumeFlowTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane tableScrollPanel;
    // End of variables declaration//GEN-END:variables
}
