/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hirwa
 */
public class MyCalculator extends javax.swing.JFrame {

    /**
     * Creates new form MyCalculator
     */
    public MyCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        CalculatorBodyPanel = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        ScreenPanel = new javax.swing.JPanel();
        InputTextField = new javax.swing.JTextField();
        AnswerTextField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        equalSignButton = new javax.swing.JButton();
        additionButton = new javax.swing.JButton();
        subtractionButton = new javax.swing.JButton();
        multiplicationButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        modulusButton = new javax.swing.JButton();
        dotButton = new javax.swing.JButton();
        number3 = new javax.swing.JButton();
        number6 = new javax.swing.JButton();
        number9 = new javax.swing.JButton();
        TanButton = new javax.swing.JButton();
        inverseTanButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        zeroButton = new javax.swing.JButton();
        number2 = new javax.swing.JButton();
        number5 = new javax.swing.JButton();
        number8 = new javax.swing.JButton();
        CosineButton = new javax.swing.JButton();
        InverseCosineButton = new javax.swing.JButton();
        TenPowerX = new javax.swing.JButton();
        plusOrMinusButton = new javax.swing.JButton();
        number1 = new javax.swing.JButton();
        number4 = new javax.swing.JButton();
        number7 = new javax.swing.JButton();
        SineButton = new javax.swing.JButton();
        inverseSineButton = new javax.swing.JButton();
        exponentValue = new javax.swing.JButton();
        Pi = new javax.swing.JButton();
        SquareRoot = new javax.swing.JButton();
        OneOverX = new javax.swing.JButton();
        xPowerY = new javax.swing.JButton();
        xPower3 = new javax.swing.JButton();
        xPower2 = new javax.swing.JButton();
        factorialButton = new javax.swing.JButton();

        jButton29.setText("=");

        jButton30.setText("+");

        jButton31.setText("-");

        jButton32.setText("x");

        jButton33.setText("/");

        jButton34.setText("mod");

        jButton35.setText("Back");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculatore Scientifica");
        setAlwaysOnTop(true);

        CalculatorBodyPanel.setBackground(new java.awt.Color(51, 51, 51));
        CalculatorBodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Scientific Calculator");
        CalculatorBodyPanel.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 18, -1, -1));

        ScreenPanel.setBackground(new java.awt.Color(153, 153, 153));
        ScreenPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        InputTextField.setBackground(new java.awt.Color(153, 153, 153));
        InputTextField.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        InputTextField.setForeground(new java.awt.Color(255, 255, 255));
        InputTextField.setBorder(null);

        AnswerTextField.setBackground(new java.awt.Color(153, 153, 153));
        AnswerTextField.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        AnswerTextField.setForeground(new java.awt.Color(255, 255, 255));
        AnswerTextField.setBorder(null);

        javax.swing.GroupLayout ScreenPanelLayout = new javax.swing.GroupLayout(ScreenPanel);
        ScreenPanel.setLayout(ScreenPanelLayout);
        ScreenPanelLayout.setHorizontalGroup(
            ScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScreenPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(InputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(AnswerTextField)))
        );
        ScreenPanelLayout.setVerticalGroup(
            ScreenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScreenPanelLayout.createSequentialGroup()
                .addComponent(InputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AnswerTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
        );

        CalculatorBodyPanel.add(ScreenPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 54, -1, -1));

        BackButton.setBackground(new java.awt.Color(102, 102, 102));
        BackButton.setForeground(new java.awt.Color(255, 255, 255));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 168, -1, -1));

        equalSignButton.setText("=");
        equalSignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalSignButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(equalSignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 63, 38));

        additionButton.setBackground(new java.awt.Color(102, 102, 102));
        additionButton.setForeground(new java.awt.Color(255, 255, 255));
        additionButton.setText("+");
        additionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(additionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 376, 63, 38));

        subtractionButton.setBackground(new java.awt.Color(102, 102, 102));
        subtractionButton.setForeground(new java.awt.Color(255, 255, 255));
        subtractionButton.setText("-");
        subtractionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractionButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(subtractionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 332, 63, 38));

        multiplicationButton.setBackground(new java.awt.Color(102, 102, 102));
        multiplicationButton.setForeground(new java.awt.Color(255, 255, 255));
        multiplicationButton.setText("x");
        multiplicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicationButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(multiplicationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 288, 63, 38));

        divisionButton.setBackground(new java.awt.Color(102, 102, 102));
        divisionButton.setForeground(new java.awt.Color(255, 255, 255));
        divisionButton.setText("/");
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(divisionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 244, 63, 38));

        modulusButton.setBackground(new java.awt.Color(102, 102, 102));
        modulusButton.setForeground(new java.awt.Color(255, 255, 255));
        modulusButton.setText("mod");
        modulusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulusButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(modulusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 63, 38));

        dotButton.setBackground(new java.awt.Color(0, 0, 0));
        dotButton.setForeground(new java.awt.Color(255, 255, 255));
        dotButton.setText(".");
        dotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(dotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 420, 73, 38));

        number3.setBackground(new java.awt.Color(0, 0, 0));
        number3.setForeground(new java.awt.Color(255, 255, 255));
        number3.setText("3");
        number3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number3ActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(number3, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 376, 70, 38));

        number6.setBackground(new java.awt.Color(0, 0, 0));
        number6.setForeground(new java.awt.Color(255, 255, 255));
        number6.setText("6");
        number6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number6ActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(number6, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 332, 73, 38));

        number9.setBackground(new java.awt.Color(0, 0, 0));
        number9.setForeground(new java.awt.Color(255, 255, 255));
        number9.setText("9");
        number9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number9ActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(number9, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 288, 73, 38));

        TanButton.setBackground(new java.awt.Color(102, 102, 102));
        TanButton.setForeground(new java.awt.Color(255, 255, 255));
        TanButton.setText("Tanh");
        TanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TanButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(TanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 244, 73, 38));

        inverseTanButton.setBackground(new java.awt.Color(102, 102, 102));
        inverseTanButton.setForeground(new java.awt.Color(255, 255, 255));
        inverseTanButton.setText("Tan^-1");
        inverseTanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inverseTanButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(inverseTanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 200, -1, 38));

        ClearButton.setBackground(new java.awt.Color(102, 102, 102));
        ClearButton.setForeground(new java.awt.Color(255, 255, 255));
        ClearButton.setText("Clear");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(ClearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 168, 73, -1));

        zeroButton.setBackground(new java.awt.Color(0, 0, 0));
        zeroButton.setForeground(new java.awt.Color(255, 255, 255));
        zeroButton.setText("0");
        zeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(zeroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 420, 74, 38));

        number2.setBackground(new java.awt.Color(0, 0, 0));
        number2.setForeground(new java.awt.Color(255, 255, 255));
        number2.setText("2");
        number2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number2ActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(number2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 376, 70, 38));

        number5.setBackground(new java.awt.Color(0, 0, 0));
        number5.setForeground(new java.awt.Color(255, 255, 255));
        number5.setText("5");
        number5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number5ActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(number5, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 332, 74, 38));

        number8.setBackground(new java.awt.Color(0, 0, 0));
        number8.setForeground(new java.awt.Color(255, 255, 255));
        number8.setText("8");
        number8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number8ActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(number8, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 288, 74, 38));

        CosineButton.setBackground(new java.awt.Color(102, 102, 102));
        CosineButton.setForeground(new java.awt.Color(255, 255, 255));
        CosineButton.setText("Cosh");
        CalculatorBodyPanel.add(CosineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 244, 74, 38));

        InverseCosineButton.setBackground(new java.awt.Color(102, 102, 102));
        InverseCosineButton.setForeground(new java.awt.Color(255, 255, 255));
        InverseCosineButton.setText("Cos^-1");
        CalculatorBodyPanel.add(InverseCosineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 200, -1, 38));

        TenPowerX.setBackground(new java.awt.Color(102, 102, 102));
        TenPowerX.setForeground(new java.awt.Color(255, 255, 255));
        TenPowerX.setText("10^x");
        CalculatorBodyPanel.add(TenPowerX, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 168, 74, -1));

        plusOrMinusButton.setBackground(new java.awt.Color(0, 0, 0));
        plusOrMinusButton.setForeground(new java.awt.Color(255, 255, 255));
        plusOrMinusButton.setText("+/-");
        CalculatorBodyPanel.add(plusOrMinusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 420, 70, 38));

        number1.setBackground(new java.awt.Color(0, 0, 0));
        number1.setForeground(new java.awt.Color(255, 255, 255));
        number1.setText("1");
        number1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number1ActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(number1, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 376, 70, 38));

        number4.setBackground(new java.awt.Color(0, 0, 0));
        number4.setForeground(new java.awt.Color(255, 255, 255));
        number4.setText("4");
        number4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number4ActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(number4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 332, 70, 38));

        number7.setBackground(new java.awt.Color(0, 0, 0));
        number7.setForeground(new java.awt.Color(255, 255, 255));
        number7.setText("7");
        number7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                number7ActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(number7, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 288, 70, 38));

        SineButton.setBackground(new java.awt.Color(102, 102, 102));
        SineButton.setForeground(new java.awt.Color(255, 255, 255));
        SineButton.setText("Sinh");
        SineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SineButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(SineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 244, 70, 38));

        inverseSineButton.setBackground(new java.awt.Color(102, 102, 102));
        inverseSineButton.setForeground(new java.awt.Color(255, 255, 255));
        inverseSineButton.setText("Sin^-1");
        inverseSineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inverseSineButtonActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(inverseSineButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 200, -1, 38));

        exponentValue.setBackground(new java.awt.Color(102, 102, 102));
        exponentValue.setForeground(new java.awt.Color(255, 255, 255));
        exponentValue.setText("e");
        CalculatorBodyPanel.add(exponentValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 168, 70, -1));

        Pi.setBackground(new java.awt.Color(102, 102, 102));
        Pi.setForeground(new java.awt.Color(255, 255, 255));
        Pi.setText("Pi");
        CalculatorBodyPanel.add(Pi, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 168, 63, -1));

        SquareRoot.setBackground(new java.awt.Color(102, 102, 102));
        SquareRoot.setForeground(new java.awt.Color(255, 255, 255));
        SquareRoot.setText("Sqrt");
        CalculatorBodyPanel.add(SquareRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 200, 63, 38));

        OneOverX.setBackground(new java.awt.Color(102, 102, 102));
        OneOverX.setForeground(new java.awt.Color(255, 255, 255));
        OneOverX.setText("1/x");
        OneOverX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OneOverXActionPerformed(evt);
            }
        });
        CalculatorBodyPanel.add(OneOverX, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 244, 63, 38));

        xPowerY.setBackground(new java.awt.Color(102, 102, 102));
        xPowerY.setForeground(new java.awt.Color(255, 255, 255));
        xPowerY.setText("x^y");
        CalculatorBodyPanel.add(xPowerY, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 288, 63, 38));

        xPower3.setBackground(new java.awt.Color(102, 102, 102));
        xPower3.setForeground(new java.awt.Color(255, 255, 255));
        xPower3.setText("x^3");
        CalculatorBodyPanel.add(xPower3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 332, 63, 38));

        xPower2.setBackground(new java.awt.Color(102, 102, 102));
        xPower2.setForeground(new java.awt.Color(255, 255, 255));
        xPower2.setText("x^2");
        CalculatorBodyPanel.add(xPower2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 376, 63, 38));

        factorialButton.setBackground(new java.awt.Color(102, 102, 102));
        factorialButton.setForeground(new java.awt.Color(255, 255, 255));
        factorialButton.setText("n!");
        CalculatorBodyPanel.add(factorialButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 420, 63, 38));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CalculatorBodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalculatorBodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotButtonActionPerformed
        // TODO add your handling code here:
        String dot = dotButton.getText();
        AnswerTextField.setText(AnswerTextField.getText()+""+dot);
    }//GEN-LAST:event_dotButtonActionPerformed

    private void multiplicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicationButtonActionPerformed
        // TODO add your handling code here:
        String choosenSign = multiplicationButton.getText();
        if(AnswerTextField.getText().length()>0){
            InputTextField.setText(InputTextField.getText()+""+AnswerTextField.getText()+""+choosenSign);
            AnswerTextField.setText("");
        }
    }//GEN-LAST:event_multiplicationButtonActionPerformed

    private void modulusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modulusButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:
        AnswerTextField.setText("");
        InputTextField.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void inverseTanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inverseTanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inverseTanButtonActionPerformed

    private void TanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TanButtonActionPerformed

    private void inverseSineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inverseSineButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inverseSineButtonActionPerformed

    private void SineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SineButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SineButtonActionPerformed

    private void OneOverXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OneOverXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OneOverXActionPerformed

    private void number1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number1ActionPerformed
        // TODO add your handling code here:
        String one = number1.getText();
        AnswerTextField.setText(AnswerTextField.getText()+""+one);
    }//GEN-LAST:event_number1ActionPerformed

    private void zeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroButtonActionPerformed
        // TODO add your handling code here:
        String zero = zeroButton.getText();
        AnswerTextField.setText(AnswerTextField.getText()+""+zero);
    }//GEN-LAST:event_zeroButtonActionPerformed

    private void number2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number2ActionPerformed
        // TODO add your handling code here:
        String two = number2.getText();
        AnswerTextField.setText(AnswerTextField.getText()+""+two);
    }//GEN-LAST:event_number2ActionPerformed

    private void number3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number3ActionPerformed
        // TODO add your handling code here:
        String three = number3.getText();
        AnswerTextField.setText(AnswerTextField.getText()+""+three);
    }//GEN-LAST:event_number3ActionPerformed

    private void number4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number4ActionPerformed
        // TODO add your handling code here:
        String four = number4.getText();
        AnswerTextField.setText(AnswerTextField.getText()+""+four);
    }//GEN-LAST:event_number4ActionPerformed

    private void number5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number5ActionPerformed
        // TODO add your handling code here:
        String five = number5.getText();
        AnswerTextField.setText(AnswerTextField.getText()+""+five);
    }//GEN-LAST:event_number5ActionPerformed

    private void number6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number6ActionPerformed
        // TODO add your handling code here:
        String six = number6.getText();
        AnswerTextField.setText(AnswerTextField.getText()+""+six);
    }//GEN-LAST:event_number6ActionPerformed

    private void number7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number7ActionPerformed
        // TODO add your handling code here:
        String seven = number7.getText();
        AnswerTextField.setText(AnswerTextField.getText()+""+seven);
    }//GEN-LAST:event_number7ActionPerformed

    private void number8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number8ActionPerformed
        // TODO add your handling code here:
        String eight = number8.getText();
        AnswerTextField.setText(AnswerTextField.getText()+""+eight);
    }//GEN-LAST:event_number8ActionPerformed

    private void number9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_number9ActionPerformed
        // TODO add your handling code here:
        String nine = number9.getText();
        AnswerTextField.setText(AnswerTextField.getText()+""+nine);
    }//GEN-LAST:event_number9ActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        String backspace = null;
        if(AnswerTextField.getText().length()>0) {
            StringBuilder str = new StringBuilder(AnswerTextField.getText());
            str.deleteCharAt(AnswerTextField.getText().length()-1);
            backspace = str.toString();
            AnswerTextField.setText(backspace);
        }
    }//GEN-LAST:event_BackButtonActionPerformed

    private void additionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionButtonActionPerformed
        // TODO add your handling code here:
        String choosenSign = additionButton.getText();
        if(AnswerTextField.getText().length()>0){
            InputTextField.setText(InputTextField.getText()+""+AnswerTextField.getText()+""+choosenSign);
            AnswerTextField.setText("");
        }
        
    }//GEN-LAST:event_additionButtonActionPerformed

    private void subtractionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractionButtonActionPerformed
        // TODO add your handling code here:
        String choosenSign = subtractionButton.getText();
        if(AnswerTextField.getText().length()>0){
            InputTextField.setText(InputTextField.getText()+""+AnswerTextField.getText()+""+choosenSign);
            AnswerTextField.setText("");
        }    
    }//GEN-LAST:event_subtractionButtonActionPerformed

    private void divisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonActionPerformed
        // TODO add your handling code here:
        String choosenSign = divisionButton.getText();
        if(AnswerTextField.getText().length()>0){
            InputTextField.setText(InputTextField.getText()+""+AnswerTextField.getText()+""+choosenSign);
            AnswerTextField.setText("");
        }
    }//GEN-LAST:event_divisionButtonActionPerformed

    private void equalSignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalSignButtonActionPerformed
        // TODO add your handling code here:
        String choosenSign = equalSignButton.getText();
        if (AnswerTextField.getText().length()>0){
            InputTextField.setText(InputTextField.getText()+""+AnswerTextField.getText()+""+choosenSign);
            
            AnswerTextField.setText("");
            
            
        }
    }//GEN-LAST:event_equalSignButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnswerTextField;
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel CalculatorBodyPanel;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton CosineButton;
    private javax.swing.JTextField InputTextField;
    private javax.swing.JButton InverseCosineButton;
    private javax.swing.JButton OneOverX;
    private javax.swing.JButton Pi;
    private javax.swing.JPanel ScreenPanel;
    private javax.swing.JButton SineButton;
    private javax.swing.JButton SquareRoot;
    private javax.swing.JButton TanButton;
    private javax.swing.JButton TenPowerX;
    private javax.swing.JLabel Title;
    private javax.swing.JButton additionButton;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton dotButton;
    private javax.swing.JButton equalSignButton;
    private javax.swing.JButton exponentValue;
    private javax.swing.JButton factorialButton;
    private javax.swing.JButton inverseSineButton;
    private javax.swing.JButton inverseTanButton;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton modulusButton;
    private javax.swing.JButton multiplicationButton;
    private javax.swing.JButton number1;
    private javax.swing.JButton number2;
    private javax.swing.JButton number3;
    private javax.swing.JButton number4;
    private javax.swing.JButton number5;
    private javax.swing.JButton number6;
    private javax.swing.JButton number7;
    private javax.swing.JButton number8;
    private javax.swing.JButton number9;
    private javax.swing.JButton plusOrMinusButton;
    private javax.swing.JButton subtractionButton;
    private javax.swing.JButton xPower2;
    private javax.swing.JButton xPower3;
    private javax.swing.JButton xPowerY;
    private javax.swing.JButton zeroButton;
    // End of variables declaration//GEN-END:variables
}
